accounts/urls.py
from django.urls import path

from .views import profile, ProfileUpdateView, SignedDataPrivacyCreateView, DisclaimerCreateView, DisclaimerContactUpdateView

app_name = 'accounts'


urlpatterns = [
    path('profile/', profile, name='profile'),
    path('update/', ProfileUpdateView.as_view(), name='update_profile'),
    path(
        'data-privacy-review/', SignedDataPrivacyCreateView.as_view(),
         name='data_privacy_review'
    ),
    path('disclaimer/<int:user_id>/', DisclaimerCreateView.as_view(), name='disclaimer_form'),
    path('emergency-contact/<int:user_id>/update/', DisclaimerContactUpdateView.as_view(), name='update_emergency_contact'),

    path('', profile)
]

booking/urls.py
from django.urls import path


from booking.views import EventListView, EventDetailView, BookingCreateView, \
    already_cancelled, already_paid, \
    BookingListView, \
    BookingHistoryListView, BookingUpdateView, \
    BookingDeleteView, update_booking_cancelled, \
    cancellation_period_past, duplicate_booking, fully_booked, \
    toggle_booking, toggle_waiting_list, booking_details, update_booking_count, \
    outstanding_fees


app_name = 'booking'


urlpatterns = [
    path('my-bookings/', BookingListView.as_view(), name='bookings'),
    path('booking-history/', BookingHistoryListView.as_view(),
        name='booking_history'),
    path('my-bookings/update/<int:pk>/', BookingUpdateView.as_view(),
        name='update_booking'),
    path('my-bookings/update/<int:pk>/cancelled/',
        update_booking_cancelled,
        name='update_booking_cancelled'),
    path('my-bookings/update/<int:pk>/paid/',
        already_paid, name='already_paid'),
    path('my-bookings/cancel/<int:pk>/', BookingDeleteView.as_view(),
        name='delete_booking'),
    path('my-bookings/cancel/<int:pk>/already_cancelled/',
        already_cancelled,
        name='already_cancelled'),
    path('workshops/<slug:event_slug>/cancellation-period-past/',
        cancellation_period_past, name='cancellation_period_past'),
    path('workshops/<slug:event_slug>/duplicate/',
        duplicate_booking, name='duplicate_booking'),
    path('workshops/<slug:event_slug>/full/', fully_booked,
        name='fully_booked'),
    path('workshops/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_event'),
    path('class/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_class'),
    path(
        'workshops/<slug:slug>/', EventDetailView.as_view(),
        name='event_detail'
    ),
    path('outstanding-fees/', outstanding_fees, name="outstanding_fees"),
    path(
        'toggle-booking/<int:event_id>/',
        toggle_booking, name='toggle_booking'
    ),
    path(
        'ajax-toggle-waiting-list/<int:event_id>/',
        toggle_waiting_list, name='toggle_waiting_list'
    ),
    path(
        'update-booking-details/<int:event_id>/',
        booking_details, name='booking_details'
    ),
    path(
        'ajax-update-booking-count/<int:event_id>/',
        update_booking_count, name='update_booking_count'
    ),
    path('', EventListView.as_view(), name='events'),
 ]

gallery/urls.py
from django.urls import path

from gallery.views import gallery


app_name = 'gallery'


urlpatterns = [
    path('', gallery, name='gallery'),
]

polefit/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import CustomLoginView, CustomSignUpView, \
    data_privacy_policy, cookie_policy
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path('', include('website.urls')),
    path(
        'accounts/signup/', CustomSignUpView.as_view(), name='account_signup'
    ),
    path(
        'accounts/login/', CustomLoginView.as_view(), name='account_login'
    ),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    re_path(r'^pf_admin.*', redirect_to_admin, name='redirect_old_link'),
    path('instructor-admin/', include('studioadmin.urls')),
    path('site-admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('payments/ipn-paypal-notify/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    path('not-available/', permission_denied, name='permission_denied'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

studioadmin/urls.py
from django.views.generic import RedirectView
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from .views.fees import outstanding_fees_user, outstanding_fees_list, \
    ajax_toggle_cancellation_fee_payment, ajax_toggle_remove_cancellation_fee, \
    ajax_get_cancellation_fee_payment_status, ajax_get_user_total_fees
from .views.register import EventRegisterListView, register_view, \
    booking_register_add_view, ajax_toggle_attended
from .views.users import UserListView, UserDisclaimerView
from .views.waiting_list import event_waiting_list_view

app_name = 'studioadmin'


urlpatterns = [
    path(
        'registers/classes/', staff_member_required(EventRegisterListView.as_view()),
        {"event_type": "regular_session"}, name="regular_session_register_list"
    ),
    path(
        'registers/workshops/', staff_member_required(EventRegisterListView.as_view()),
        {"event_type": "workshop"}, name="workshop_register_list"
    ),
    path('registers/<slug:event_slug>/', register_view, name='event_register'),
    path('registers/add-booking/<int:event_id>/', booking_register_add_view, name='bookingregisteradd'),
    path('registers/<int:booking_id>/toggle_attended/', ajax_toggle_attended, name='ajax_toggle_attended'),
    path('waiting-list/<slug:event_slug>/', event_waiting_list_view, name="event_waiting_list"),
    path('students/', staff_member_required(UserListView.as_view()), name="user_list"),
    path('student/<int:pk>/disclaimer/', staff_member_required(UserDisclaimerView.as_view()), name="user_disclaimer"),
    path('fees/<int:user_id>/', outstanding_fees_user, name="user_fees"),
    path(
        'fees/ajax-toggle-cancellation-fee-payment/<int:booking_id>/',
        ajax_toggle_cancellation_fee_payment, name="ajax_toggle_cancellation_fee_payment"
    ),
    path(
        'fees/ajax-toggle-remove-cancellation-fee/<int:booking_id>/',
        ajax_toggle_remove_cancellation_fee, name="ajax_toggle_remove_cancellation_fee"
    ),
    path(
        'fees/ajax-cancellation-fee-payment-status/<int:booking_id>/',
        ajax_get_cancellation_fee_payment_status, name="ajax_get_cancellation_fee_payment_status"
    ),
    path(
        'fees/ajax-user-total-fees/<int:user_id>/',
        ajax_get_user_total_fees, name="ajax_get_user_total_fees"
    ),
    path('fees/', outstanding_fees_list, name="outstanding_fees"),
    path('', RedirectView.as_view(url='/instructor-admin/registers/classes/', permanent=True)),
]

timetable/urls.py
from django.urls import path

from timetable.views import TimetableListView


app_name = 'timetable'


urlpatterns = [
    path('', TimetableListView.as_view(), name='timetable'),
]

website/urls.py
from django.urls import path
from django.views.generic import RedirectView

from website.views import about, \
    booking_request, classes, contact, \
    contact_form, instructors, \
    membership, parties, venues

app_name = 'website'

urlpatterns = [
    path('about/', about, name='about'),
    path('classes/', classes, name='classes'),
    path('<int:session_pk>/book/', booking_request,
        name='booking_request'),
    path('instructors/', instructors, name='instructors'),
    path('venues/', venues, name='venues'),
    path('membership/', membership, name='membership'),
    path('parties/', parties, name='parties'),
    path('contact-form/', contact_form, name='contact_form'),
    path('contact/', contact, name='contact'),
    path('', RedirectView.as_view(url='/about/', permanent=True)),
]

booking/views/event_views.py
import logging
import pytz

from collections import OrderedDict

from django.shortcuts import HttpResponseRedirect, render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.http import Http404

from booking.forms import EventsFilter
from booking.models import Booking, Event, WaitingListUser


logger = logging.getLogger(__name__)


DAYS = OrderedDict((
    ('01MO', 'Monday'),
    ('02TU', 'Tuesday'),
    ('03WE', 'Wednesday'),
    ('04TH', 'Thursday'),
    ('05FR', 'Friday'),
    ('06SA', 'Saturday'),
    ('07SU', 'Sunday')
))


class EventListView(ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'booking/regular_classes.html'
    paginate_by = 20

    def get_queryset(self):
        self.event_type = self.request.GET.get('type', 'regular_session').strip()
        name = self.request.GET.get('name', 'all').strip()
        level = self.request.GET.get('level')
        if name and level:
            self.event_name = '{} ({})'.format(name, level.strip())
        else:
            self.event_name = name
        self.venue = self.request.GET.get('venue', 'all').strip()
        self.event_day = self.request.GET.get('day', '').strip()
        self.event_time = self.request.GET.get('time', '').strip()

        # show all future events for staff users
        if self.request.user.is_staff:
            events = Event.objects.filter(
                event_type=self.event_type, date__gte=timezone.now()
            ).order_by('date')
        else:
            events = Event.objects.filter(
                event_type=self.event_type, date__gte=timezone.now(), show_on_site=True
            ).order_by('date')

        if self.event_name != 'all':
            events = events.filter(name=self.event_name)
        if self.venue != 'all':
            events = events.filter(venue__abbreviation=self.venue)

        # select day/time
        if self.event_day in DAYS.keys() and self.event_time:
            weekday = list(DAYS.keys()).index(self.event_day)
            try:
                event_time = self.event_time.split(':')
                hour = int(event_time[0])
                min = int(event_time[1])
            except (ValueError, IndexError):
                self.event_time = None
            else:
                localtz = pytz.timezone('Europe/London')
                event_ids = [
                    event.id for event in events if event.date.weekday() == weekday
                    and event.date.minute == min
                    and event.date.hour == hour - (event.date.astimezone(localtz).dst().seconds / 3600)
                ]
                events = events.filter(id__in=event_ids)
        return events

    def paginate_queryset(self, queryset, page_size):
        """Paginate the queryset, if needed."""
        try:
            resp = super().paginate_queryset(queryset, page_size)
        except Http404:
            paginator = self.get_paginator(
                queryset, page_size, orphans=self.get_paginate_orphans(),
                allow_empty_first_page=self.get_allow_empty()
            )
            page = paginator.page(1)
            return paginator, page, page.object_list, page.has_other_pages()
        return resp

    def get_context_data(self, **kwargs):
        queryset = self.object_list
        # Call the base implementation first to get a context
        context = super(EventListView, self).get_context_data(**kwargs)
        context['section'] = 'events'
        if not self.request.user.is_anonymous:
            # Add in the booked_events
            user_booked_events = Booking.objects.select_related()\
                .filter(user=self.request.user, status='OPEN', no_show=False)\
                .values_list('event__id', flat=True)
            booked_events = queryset.filter(id__in=user_booked_events).values_list('id', flat=True)
            waiting_list_events = WaitingListUser.objects\
                .filter(user=self.request.user)\
                .values_list('event__id', flat=True)
            context['booked_events'] = booked_events
            context['waiting_list_events'] = waiting_list_events
        if self.request.user.is_staff:
            # add in the staff-only events
            context['staff_only_events'] = queryset.filter(
                show_on_site=False
            ).values_list('id', flat=True)

        if self.event_type == 'regular_session':
            alternative_events = Event.objects.filter(
                event_type='workshop', date__gte=timezone.now(), cancelled=False
            )
        else:
            alternative_events = Event.objects.filter(
                event_type='regular_session', date__gte=timezone.now(), cancelled=False
            )

        if not self.request.user.is_staff:
            alternative_events = alternative_events.filter(show_on_site=True)

        context['workshops_available_to_book'] = alternative_events.exists() if self.event_type == 'regular_session' else None
        context['classes_available_to_book'] = alternative_events.exists() if self.event_type == 'workshop' else None

        form = EventsFilter(
            event_type=self.event_type,
            initial={'name': self.event_name, 'venue': self.venue}
        )

        context['form'] = form
        context['name'] = self.event_name
        context['day'] = DAYS.get(self.event_day, None)
        context['venue'] = self.venue
        context['time'] = self.event_time
        return context

    def get_template_names(self):
        if self.event_type == 'workshop':
            return 'booking/events.html'
        else:
            return self.template_name


class EventDetailView(DetailView):

    model = Event
    context_object_name = 'event'
    template_name = 'booking/event.html'

    def get_object(self):
        if self.request.user.is_staff:
            return get_object_or_404(Event, slug=self.kwargs['slug'])
        return get_object_or_404(
            Event, slug=self.kwargs['slug'], show_on_site=True
        )

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EventDetailView, self).get_context_data()
        event = self.object
        event_type = 'class' if event.event_type == 'regular_session' else 'workshop'
        user = self.request.user

        context['event_type'] = event_type

        if event.date <= timezone.now():
            context['past'] = True

        # booked/cancelled flags
        if not self.request.user.is_anonymous:
            booked = False
            cancelled = False
            try:
                existing_booking = Booking.objects.get(event=event, user=user)
            except Booking.DoesNotExist:
                existing_booking = None

            if existing_booking:
                if existing_booking.status == 'OPEN':
                    if existing_booking.no_show:
                        cancelled = True
                    else:
                        booked = True
                else:
                    cancelled = True

            # waiting_list flag
            try:
                WaitingListUser.objects.get(user=user, event=event)
                context['waiting_list'] = True
            except WaitingListUser.DoesNotExist:
                pass

            # booking info text and bookable
            booking_info_text = ''
            context['bookable'] = event.bookable
            if booked:
                context['bookable'] = False
                booking_info_text = "You have booked for this " \
                                    "{}.".format(event_type)
                context['booked'] = True
            else:
                if cancelled:
                    context['cancelled'] = True
                    cancelled_text = "You have previously booked " \
                                                  "for this {} and your booking " \
                                                  "has been " \
                                                  "cancelled.".format(event_type)
                    context['booking_info_text_cancelled'] = cancelled_text

                if event.spaces_left <= 0:
                    booking_info_text = "This {} is now full.".format(event_type)
        else:
            login_url_str = "/accounts/login?next=/booking/{}s/{}".format(
                event_type, event.slug
            )
            if event.spaces_left <= 0:
                booking_info_text = mark_safe(
                    "This {} is now full.  "
                    "Please <a href='{}'>log in</a> to join the waiting "
                    "list.".format(event_type, login_url_str)
                )
            else:
                booking_info_text = mark_safe(
                    "Please <a href='{}'>log in</a> to book.".format(
                        login_url_str
                    )
                )
        context['booking_info_text'] = booking_info_text
        return context

website/templates/website/_base.html
{% load static %}
{% load bootstrap3 %}
{% load cookielaw_tags %}


<!DOCTYPE html>
<html lang="en" class="{% block bg_class %}logo_bg{%  endblock %}">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=0.65">
        <title>Carousel Fitness</title>

        <link rel="icon" type="image/png" href="{% static 'website/images/logo_no_text_transparent.png' %}">
        <link rel="shortcut icon" href="{% static 'website/images/favicon.ico' %}" type="image/vnd.microsoft.icon">

        <!-- Bootstrap core CSS -->
        {% bootstrap_css %}

        <link href="{% static 'website/css/custom-v3.css' %}" rel="stylesheet">
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
         <!--<link rel="stylesheet" href="{% static 'website/bootstrap/font-awesome.min.css' %}">-->

        {% block extrahead %}{% endblock %}

    </head>
<body>

    <div class="wrap">
        <!-- Fixed navbar -->
        <div style="margin-top: 45px" class="navbar navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" rel="home" href="/" title="Carousel Fitness">
                        <img  style="max-width:150px; margin-top: -58px; margin-left: 0; padding-left: 0;" src="{% static "website/images/logo_wide_no_text.jpg" %}">
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav pull-left">
                        <li><a {% if section == 'about' %}class="active"{% endif %} href="{% url 'website:about' %}">About us</a></li>
                        <li><a {% if section == 'timetable' %}class="active"{% endif %} href="{% url 'timetable:timetable' %}">Timetable</a></li>
                        <li class = "hidden-sm"><a {% if section == 'classes' %}class="active"{% endif %} href="{% url 'website:classes' %}">Classes</a></li>
                        <li><a {% if section == 'events' %}class="active"{% endif %} href="{% url 'booking:events' %}">Book</a></li>
                        <li class="hidden-sm hidden-md"><a {% if section == 'membership' %}class="active"{% endif %} href="{% url 'website:membership' %}">Membership</a></li>
                        <li class = "hidden-sm hidden-md"><a {% if section == 'instructors' %}class="active"{% endif %} href="{% url 'website:instructors' %}">Instructors</a></li>
                        <li class = "hidden-sm hidden-md"><a {% if section == 'venues' %}class="active"{% endif %} href="{% url 'website:venues' %}">Venues</a></li>
                        <li class = "hidden-sm hidden-md" ><a {% if section == 'parties' %}class="active"{% endif %} href="{% url 'website:parties' %}">Parties</a></li>
                        <li class = "hidden-sm hidden-md " ><a {% if section == 'gallery' %}class="active"{% endif %} href="{% url 'gallery:gallery' %}">Gallery</a></li>
                        <li ><a {% if section == 'contact' %}class="active"{% endif %} href="{% url 'website:contact' %}">Contact us</a></li>
                        <li class="visible-sm visible-md dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                          <ul class="dropdown-menu">
                                <li class="hidden-md"><a href="{% url 'website:classes' %}">Classes</a></li>
                                <li><a href="{% url 'website:instructors' %}">Instructors</a></li>
                                <li><a href="{% url 'website:venues' %}">Venues</a></li>
                                <li><a href="{% url 'website:parties' %}">Parties</a></li>
                                <li><a href="{% url 'gallery:gallery' %}">Gallery</a></li>
                              <li><a href="{% url 'website:membership' %}">Membership</a></li>
                          </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        {% if user.is_authenticated %}
                        <li class="dropdown pull-right">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account<b class="caret"></b></a>
                          <ul class="dropdown-menu pull-right">
                                <li><a class="account-menu-option" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="account-menu-option" href="{% url 'account_change_password' %}">Change password</a></li>
                                <li><a class="account-menu-option" href="{% url 'booking:bookings' %}">Bookings</a></li>
                                <li><a class="account-menu-option" href="{% url 'booking:booking_history' %}">Past bookings</a></li>
                                <li><a class="account-menu-option" href="{% url 'account_logout' %}">Log out</a></li>
                                {% if user.is_staff %}
                                    <li><a class="account-menu-option" href="{% url 'studioadmin:regular_session_register_list' %}">Instructor Admin</a></li>
                                {% endif %}
                                {% if user.is_superuser %}
                                    <li><a class="account-menu-option" href="{% url 'admin:index' %}">Site Admin</a></li>
                                {% endif %}

                          </ul>
                        </li>
                      {% else %}
                        <li class="pull-right"><a href="{% url 'account_login' %}">Log in</a></li>
                      {% endif %}

                   </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        {% cookielaw_banner %}

        {% if messages %}
            <div class="extra-top-margin col-xs-12">
                {% for message in messages %}
                <div {% if message.tags and message.tags == 'error' %}
                            class="message alert alert-danger"
                     {% elif message.tags %}
                            class="message alert alert-{{ message.tags }}"
                     {% endif %}>
                    {% if 'safe' in message.tags %}
                        {{ message|safe }}
                    {% else %}
                        {{ message }}
                    {% endif %}</div>
                {% endfor %}
            </div>
        {% endif %}

    <div class="container-fluid mt-2">
        <div class="message alert alert-warning alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <p>We have made the decision that it is the end of the road for Carousel Fitness.  We are ready to put our all into our own ventures.</p>

            <p>We understand that Carousel has been a big part of many peoples lives and we are so grateful to everyone who has attended classes with us and helped pull us through these last few months.</p>

            <p>Although it is the end of an era we know this is the right decision for us. Carousel will always hold a special place in our heart, as will all our students.</p>

            <p>We want to say a huge thank you to everyone and we are very excited to move onto the next chapter in our lives.</p>

            <p>We love you and appreciate you.</p>

            <p>Don't forget to check out <a href="https://www.facebook.com/FitnesswithemmaJ">Fitness with Emma</a> on Facebook to keep up to date with Emma and <a href="https://www.instagram.com/sunshinefitnessfife/">Sunshine Fitness</a> on Instagram for Kira.</p>

            <p>We will keep the Carousel pages going for another month so please save any photos or posts that you like before the pages come down.</p>

            <p>We love and appreciate you all,</p>

            <p>Emma and Kira</p>


        </div>

    </div>


        {% block content %}
        <p>You need to define a content block!</p>
        {% endblock %}

<!--/.footer -->
    <div class="push">
    </div>
    </div> <!--/end of page .wrap -->

    <div class="footer">
            <span class="divider"></span>

        <div class="container-fluid">
            <div class="row footer_box">
                <div class="col-sm-5 pull-left">
                    <div class="footer-fb">
                    <a href="https://www.facebook.com/carouselfitness">
                        <span class="fab fa-facebook-square"></span> Visit us on Facebook
                    </a>
                    </div>
                    <div class="footer-credit">Site developed by <a href="https://twitter.com/rebkwok" target="_blank" style="color: #0B0B61">Becky Smith</a></div>
                    <div class="footer-credit"><a href="{% url 'data_privacy_policy' %}">Data Privacy Policy</a></div>
                </div>
                <div class="col-sm-4">
                    <div class="footer-link-box"><a class="footer-link" href="{% url 'timetable:timetable' %}">Find a class</a></div>
		            <div class="footer-link-box"><a class="footer-link" href="{% url 'website:contact' %}">Contact us</a></div>
                </div>


                <div class="hidden-xs col-sm-3 footer-logo pull-right">
                    <img class="pull-right img-responsive" style="max-height:50px; margin-bottom:5px"; src="{% static "website/images/logo_text_only.png" %}">
                </div>
            </div>
        </div>
    </div>

</body>


    <!-- Google analytics
    ======================================================-->
    <!--<script>-->
          <!--(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){-->
          <!--(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),-->
          <!--m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)-->
          <!--})(window,document,'script','//www.google-analytics.com/analytics.js','ga');-->

          <!--ga('create', 'UA-51541461-1', 'auto');-->
          <!--ga('send', 'pageview');-->

    <!--</script>-->

   <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% bootstrap_javascript jquery=3 %}

    <div id="fb-root"></div>
    <script src="{% static "website/js/custom-v3.js" %}"></script>
    <script src="{% static "website/js/ajax_csrf.js" %}"></script>
    <script src="{% static 'cookielaw/js/cookielaw.js' %}"></script>

    {% block extrascripts %}{% endblock %}

</html>

website/templates/website/classes.html
{% extends "website/_base.html" %}

{% block content %}

<div class="container-fluid reduce-top-margin">
    <div class="page-header col-xs-12">
        <h1>Classes</h1>
    </div>


    <div class="col-xs-12">

        <p>For details of specific classes and to book, please see the <a href="{% url 'timetable:timetable' %}">timetable</a>.</p>
		<p>For membership queries, private lessons/one-to-one tuition, or any other enquiries, please <a href="{% url 'website:contact_form' %}">contact us</a>.</p>
        </p>
    </div>

    <div class="container">
    {% for selected_session in session_types %}

    {% if selected_session.photo %}
        <div class="row">

            <div class="col-sm-5">
                <h3>{{ selected_session.name }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <p>{{ selected_session.info|linebreaks}}</p>
                <p>Click <a href="{% url 'timetable:timetable' %}">here</a> to view class timetable and book.</p>
            </div>
            <div class="col-sm-6 img-container">
                <img src="{{ MEDIA_URL }}{{ selected_session.photo.name }}" title="{{ selected_session.name }} class"
                     alt="{{ selected_session.name }} image" class="img-responsive"><br/>
            </div>
        </div>
    {% else %}

        <div class="col-sm-12">
                <h3>{{ selected_session.name }}</h3>
                <p>{{ selected_session.info|linebreaks }}</p>

        </div>
    {% endif %}
    {% endfor %}
        </div>
</div>

{%  endblock %}

website/templates/website/contact_us.html
{% extends 'website/_base.html' %}

{% block content %}

<div class="container-fluid reduce-top-margin">
	<div class="row">
		<div class="page-header col-xs-12">
			<h1>Contact us</h1>
        </div>
		<div class="col-xs-12">
            <h3>Class Bookings</h3>
                <p>For details of specific classes and to book, please see the
                    <a href="{% url 'timetable:timetable' %}">timetable</a>.</p>

            <h3>Other enquiries</h3>

                <p>For enquiries about classes, membership options, private
                    or party bookings, or any other questions, please use our contact form below:</p>
                <div class="panel panel-booking">
                    {% include 'website/contact_form_detail.html' %}
                </div>


            <h3>Email</h3>
                <p>You can also contact us by email at <a href="mailto:carouselfitness@gmail.com" target="_blank">
				carouselfitness@gmail.com</a>.</p>
        </div>
    </div>
</div>

{% endblock %}