booking/urls.py
from django.urls import path


from booking.views import EventListView, EventDetailView, BookingCreateView, \
    already_cancelled, already_paid, \
    BookingListView, \
    BookingHistoryListView, BookingUpdateView, \
    BookingDeleteView, update_booking_cancelled, \
    cancellation_period_past, duplicate_booking, fully_booked, \
    toggle_booking, toggle_waiting_list, booking_details, update_booking_count, \
    outstanding_fees


app_name = 'booking'


urlpatterns = [
    path('my-bookings/', BookingListView.as_view(), name='bookings'),
    path('booking-history/', BookingHistoryListView.as_view(),
        name='booking_history'),
    path('my-bookings/update/<int:pk>/', BookingUpdateView.as_view(),
        name='update_booking'),
    path('my-bookings/update/<int:pk>/cancelled/',
        update_booking_cancelled,
        name='update_booking_cancelled'),
    path('my-bookings/update/<int:pk>/paid/',
        already_paid, name='already_paid'),
    path('my-bookings/cancel/<int:pk>/', BookingDeleteView.as_view(),
        name='delete_booking'),
    path('my-bookings/cancel/<int:pk>/already_cancelled/',
        already_cancelled,
        name='already_cancelled'),
    path('workshops/<slug:event_slug>/cancellation-period-past/',
        cancellation_period_past, name='cancellation_period_past'),
    path('workshops/<slug:event_slug>/duplicate/',
        duplicate_booking, name='duplicate_booking'),
    path('workshops/<slug:event_slug>/full/', fully_booked,
        name='fully_booked'),
    path('workshops/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_event'),
    path('class/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_class'),
    path(
        'workshops/<slug:slug>/', EventDetailView.as_view(),
        name='event_detail'
    ),
    path('outstanding-fees/', outstanding_fees, name="outstanding_fees"),
    path(
        'toggle-booking/<int:event_id>/',
        toggle_booking, name='toggle_booking'
    ),
    path(
        'ajax-toggle-waiting-list/<int:event_id>/',
        toggle_waiting_list, name='toggle_waiting_list'
    ),
    path(
        'update-booking-details/<int:event_id>/',
        booking_details, name='booking_details'
    ),
    path(
        'ajax-update-booking-count/<int:event_id>/',
        update_booking_count, name='update_booking_count'
    ),
    path('', EventListView.as_view(), name='events'),
 ]

polefit/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import CustomLoginView, CustomSignUpView, \
    data_privacy_policy, cookie_policy
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path('', include('website.urls')),
    path(
        'accounts/signup/', CustomSignUpView.as_view(), name='account_signup'
    ),
    path(
        'accounts/login/', CustomLoginView.as_view(), name='account_login'
    ),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    re_path(r'^pf_admin.*', redirect_to_admin, name='redirect_old_link'),
    path('instructor-admin/', include('studioadmin.urls')),
    path('site-admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('payments/ipn-paypal-notify/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    path('not-available/', permission_denied, name='permission_denied'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

timetable/urls.py
from django.urls import path

from timetable.views import TimetableListView


app_name = 'timetable'


urlpatterns = [
    path('', TimetableListView.as_view(), name='timetable'),
]

website/urls.py
from django.urls import path
from django.views.generic import RedirectView

from website.views import about, \
    booking_request, classes, contact, \
    contact_form, instructors, \
    membership, parties, venues

app_name = 'website'

urlpatterns = [
    path('about/', about, name='about'),
    path('classes/', classes, name='classes'),
    path('<int:session_pk>/book/', booking_request,
        name='booking_request'),
    path('instructors/', instructors, name='instructors'),
    path('venues/', venues, name='venues'),
    path('membership/', membership, name='membership'),
    path('parties/', parties, name='parties'),
    path('contact-form/', contact_form, name='contact_form'),
    path('contact/', contact, name='contact'),
    path('', RedirectView.as_view(url='/about/', permanent=True)),
]

timetable/models.py
from django.db import models


class Instructor(models.Model):
    index = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=255)
    info = models.TextField('instructor description', blank=True, null=True)
    regular_instructor = models.BooleanField(
        default=True,
        help_text="Tick this box to list this instructor on the "
                  "Instructors webpage"
    )
    photo = models.ImageField(
        upload_to='instructors', null=True,
        blank=True, help_text="Please upload a .jpg image with equal height "
                              "and width. File size must be less than 2Mb."
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # delete old image file when replacing by updating the file
        try:
            this = Instructor.objects.get(id=self.id)
            if this.photo != self.photo:
                this.photo.delete(save=False)
        except: pass # when new photo then we do nothing, normal case
        super(Instructor, self).save(*args, **kwargs)


class SessionType(models.Model):
    index = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=255)
    info = models.TextField('session description',  null=True)
    regular_session = models.BooleanField(
        'display session', default=True,
        help_text="Tick this box to list this class type on the homepage "
                  "and class description pages")
    photo = models.ImageField(
        upload_to='sessions', null=True, blank=True,
        help_text="File size must be less than 2Mb"
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # delete old image file when replacing by updating the file
        try:
            this = SessionType.objects.get(id=self.id)
            if this.photo != self.photo:
                this.photo.delete(save=False)
        except: pass # when new photo then we do nothing, normal case
        super(SessionType, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "class"
        verbose_name_plural = "classes"


class Venue(models.Model):
    venue = models.CharField(max_length=255, default="Venue TBC")
    address = models.CharField(max_length=255, null=True, blank=True)
    postcode = models.CharField(max_length=255, null=True, blank=True)
    abbreviation = models.CharField(max_length=20, default="")

    def __str__(self):
        return self.venue


MEMBERSHIP_CATEGORY_CHOICES = (
    ("1", "Pole and hoop classes"),
    ("2", "General fitness and conditioning classes"),
    ("3", "Open training")
)


class TimetableSession(models.Model):
    level = models.CharField(max_length=255, default="All levels")

    MON = '01MO'
    TUE = '02TU'
    WED = '03WE'
    THU = '04TH'
    FRI = '05FR'
    SAT = '06SA'
    SUN = '07SU'
    WEEKDAY_CHOICES = (
        (MON, 'Monday'),
        (TUE, 'Tuesday'),
        (WED, 'Wednesday'),
        (THU, 'Thursday'),
        (FRI, 'Friday'),
        (SAT, 'Saturday'),
        (SUN, 'Sunday'),

    )
    session_day = models.CharField(max_length=4, choices=WEEKDAY_CHOICES)
    start_time = models.TimeField()
    end_time = models.TimeField()
    instructor = models.ForeignKey(
        Instructor, null=True, blank=True, on_delete=models.SET_NULL
    )
    name = models.CharField(max_length=255, default="")
    session_type = models.ForeignKey(SessionType, on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    membership_category = models.CharField(
        max_length=1, help_text="Specify type of class for membership purposes",
        null=True, blank=True, choices=MEMBERSHIP_CATEGORY_CHOICES)
    cost = models.DecimalField(
        max_digits=8, decimal_places=2, default=7,
        help_text="Cost for non-members"
    )
    alt_cost = models.DecimalField(
        max_digits=8, decimal_places=2, null=True, blank=True,
        verbose_name="Member cost",
        help_text="Cost for additional session for members"
    )
    max_participants = models.PositiveIntegerField(default=12)
    cancellation_fee = models.DecimalField(max_digits=8, decimal_places=2, default=1.00)
    members_only = models.BooleanField(default=False, help_text="Classes are only available to students with memberships")
    show_on_timetable_page = models.BooleanField(default=True, help_text="Display this session on the website timetable page")

    def __str__(self):

        return "{} ({}), {}, {} {}".format(
            self.name, self.level, self.venue.abbreviation,
            (dict(self.WEEKDAY_CHOICES))[self.session_day],
            self.start_time.strftime('%H:%M')
        )

timetable/forms.py
from datetime import datetime, date

from django import forms
from django.utils import timezone

from timetable.models import TimetableSession


def get_session_types():

    def callable():
        SESSION_TYPE_CHOICES = list(
            TimetableSession.objects.select_related(
                'venue', 'session_type'
            ).distinct().order_by('session_type__index')
            .values_list('session_type__id', 'session_type__name')
        )
        SESSION_TYPE_CHOICES.insert(0, (0, 'All class types'))
        return tuple(SESSION_TYPE_CHOICES)

    return callable


def get_venues():

    def callable():
        VENUE_CHOICES = list(
            TimetableSession.objects.select_related(
                'venue', 'session_type'
            ).distinct()
            .values_list('venue__abbreviation', 'venue__abbreviation')
        )
        VENUE_CHOICES.insert(0, ('all', 'All locations'))
        return tuple(VENUE_CHOICES)

    return callable


class TimetableFilter(forms.Form):
    filtered_session_type = forms.ChoiceField(
        choices=get_session_types(),
        widget=forms.Select(attrs={'class': 'form-control input-xs'})
    )

    filtered_venue = forms.ChoiceField(
        choices=get_venues(),
        widget=forms.Select(attrs={'class': 'form-control input-xs'})
    )
    

class UploadTimetableForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(UploadTimetableForm, self).__init__(*args, **kwargs)

        qs = TimetableSession.objects.all().order_by('session_day', 'start_time')

        self.fields['start_date'] = forms.DateField(
            label="Start Date",
            widget=forms.DateInput(
                attrs={
                    'class': "form-control",
                    'id': 'datepicker_startdate',
                    'autocomplete': 'off'
                },
                format='%a %d %b %Y'
            ),
            required=True,
            initial=date.today()
        )

        self.fields['end_date'] = forms.DateField(
            label="End Date",
            widget=forms.DateInput(
                attrs={
                    'class': "form-control",
                    'id': 'datepicker_enddate',
                    'autocomplete': 'off'
                },
                format='%a %d %b %Y'
            ),
            required=True,
        )

        self.fields['show_on_site'] = forms.BooleanField(
            initial=True, help_text='(Classes will be available immediately for booking)',
            required=False
        )

        self.fields['select/deselect all'] = forms.BooleanField(
            initial=True,
            widget=forms.CheckboxInput(attrs={'id': 'select-all'}),
            required=False
        )

        self.fields['sessions'] = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple(
                attrs={'class': 'select-checkbox'}
            ),
            label="Choose sessions to upload",
            queryset=qs,
            initial=TimetableSession.objects.values_list('id', flat=True),
            required=True
        )

    def clean(self):
        super(UploadTimetableForm, self).clean()
        cleaned_data = self.cleaned_data

        start_date = self.data.get('start_date')
        if start_date:
            if self.errors.get('start_date'):
                del self.errors['start_date']
            try:
                start_date = datetime.strptime(start_date, '%a %d %b %Y').date()
                if start_date >= timezone.now().date():
                    cleaned_data['start_date'] = start_date
                else:
                    self.add_error('start_date',
                                   'Must be in the future')
            except ValueError:
                self.add_error(
                    'start_date', 'Invalid date format.  Select from '
                                        'the date picker or enter date in the '
                                        'format e.g. Mon 08 Jun 2015')

        end_date = self.data.get('end_date')
        if end_date:
            if self.errors.get('end_date'):
                del self.errors['end_date']
            try:
                end_date = datetime.strptime(end_date, '%a %d %b %Y').date()
            except ValueError:
                self.add_error(
                    'end_date', 'Invalid date format.  Select from '
                                        'the date picker or enter date in the '
                                        'format ddd DD Mmm YYYY (e.g. Mon 15 Jun 2015)')

        if not self.errors.get('end_date') and not self.errors.get('start_date'):
            if end_date >= start_date:
                cleaned_data['end_date'] = end_date
            else:
                self.add_error('end_date',
                                   'Cannot be before start date')
        return cleaned_data

timetable/views.py
from functools import wraps

from django.views.generic import ListView
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

from timetable.models import TimetableSession, Venue
from timetable.forms import TimetableFilter


def superuser_required(func):
    def decorator(request, *args, **kwargs):
        if request.user.is_superuser:
            return func(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('permission_denied'))
    return wraps(func)(decorator)


class TimetableListView(ListView):
    model = TimetableSession
    context_object_name = 'timetable_sessions'
    template_name = 'timetable/timetable.html'

    def get_queryset(self):
        queryset = TimetableSession.objects.filter(show_on_timetable_page=True).select_related(
            'venue', 'session_type'
        ).order_by(
                'session_day', 'start_time', 'venue'
        )
        session_type = self.request.GET.get('filtered_session_type', 0)
        session_type = int(session_type)
        venue = self.request.GET.get('filtered_venue', 'all')

        if session_type != 0:
            queryset = queryset.filter(session_type__id=session_type)
        if venue != 'all':
            queryset = queryset.filter(venue__abbreviation=venue)

        return queryset

    def get_context_data(self, *args, **kwargs):
        # Call the base implementation first to get a context
        context = super(TimetableListView, self).get_context_data(**kwargs)
        context['section'] = 'timetable'
        context['venues'] = Venue.objects.all()

        session_type = self.request.GET.get('filtered_session_type', 0)
        session_type = int(session_type)
        venue = self.request.GET.get('filtered_venue', 'all')

        form = TimetableFilter(
            initial={
                'filtered_session_type': session_type, 'filtered_venue': venue
            }
        )

        context['form'] = form
        return context

timetable/templates/timetable/timetable.html
{% extends "website/_base.html" %}
{% load customtags %}

{% block content %}
<div class="reduce-top-margin">

    <div class="page-header fixed-table" >
        <h2>
            Timetable
        </h2>
    </div>

    {% if timetable_sessions %}


        <form class="filter-row" action="" method="get">
            <div class="row">
                <div class="col-sm-2">
                    <strong>Show classes by: </strong>
                </div>
                <div class="col-sm-2 filter">{{ form.filtered_session_type }}</div>
                <div class="col-sm-2 filter">{{ form.filtered_venue }}</div>
                <div class="col-sm-1"><input class="btn btn-info table-btn" type="submit" value="Go" /></div>
            </div>
        </form>
        </br>

        <div>
            <div class="panel" style="background-color: rgba(230,230,230,0.6);">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Day</th>
                            <th>Time</th>
                            <th>Class <span class="help-text" style="white-space: nowrap;"></br>
                                <a href="{% url 'website:classes' %}">Class information</a></span>
                            </th>
                            <th>Cost
                                <span data-toggle="tooltip" title="Drop-in Cost for members/non-members">
                                  <i class="fas fa-info-circle"></i>
                                </span>
                                <span class="help-text" style="white-space: nowrap;"></br>
                                <a href="{% url 'website:membership' %}">Membership options</a></span>
                            </th>
                            <th>Level</th>
                            <th>Venue <span class="help-text" style="white-space: nowrap;"></br>
                                <a href="{% url 'website:venues' %}">Venue locations</a></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for session in timetable_sessions %}
                        <tr
                            {% if session.venue.venue == "The Watermelon Studio" %}
                                class="venue-edinburgh"
                            {% elif session.venue.venue == "Carousel Fitness Studio" %}
                                class="venue-inverkeithing"
                            {% elif session.venue.venue == "Cowdenbeath Studio" %}
                                class="venue-cowdenbeath"
                            {% elif session.venue.venue == "Energy Zone" %}
                                class="venue-energyzone"
                            {% endif %}>
                            <td class="table-center timetable-row">
                                <!--<a href="{% url 'website:booking_request' session.pk %}">-->
                                <a href="{% url 'booking:events' %}?name={{session.name}}&level={{session.level}}&venue={{session.venue.abbreviation}}&day={{session.session_day}}&time={{session.start_time|date:'H:i'}}">
                                <div class="btn btn-info table-btn booking-btn">View Dates</div></a>
                            </td>
                            <td class="timetable-row">{{ session.session_day|format_day }}</td>
                            <td class="timetable-row">{{ session.start_time|time:"H:i" }} - {{ session.end_time|time:"H:i" }}</td>
                            <td class="table-center timetable-row">
                                {% if session.membership_category == "1" %}
                                    <span class="membership-label label label-warning label-rounded">
                                {% elif session.membership_category == "2" %}
                                    <span class="membership-label label label-success label-rounded">
                                {% elif session.membership_category == "3" %}
                                    <span class="membership-label label label-primary label-rounded">
                                {% else %}
                                    <span>
                                {% endif %}
                                    {{ session.name }}
                                </span></td>
                            <td class="table-center timetable-row">
                                {% if session.members_only %}
                                Membership only
                                {% else %}
                                £ {{ session.cost | format_cost }}{% if session.alt_cost %} / £ {{ session.alt_cost | format_cost }}{% endif %}</td>
                                {% endif %}
                        <td class="timetable-row session-level-td">{{ session.level }}</td>
                            <td class="timetable-row">{{ session.venue.abbreviation }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    {% else %}
        <h4>Timetable not currently available</h4>
    {% endif %}
</div>


{% endblock %}

timetable/templates/timetable/upload_timetable_confirmation.html
{% extends "admin/base.html" %}
{% load static %}

{% block extrastyle %}
<link href="{% static 'website/css/admin-extra.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container-fluid row admin-center">

<div class="small-margin extra-top-margin container-fluid row">
    <div class="col-sm-11">
        <div>
            <h4>Classes uploaded from the current timetable</h4>
            <p><strong>Start date:</strong> {{ start_date | date:"D d F Y"}}</p>
            <p><strong>End date:</strong> {{ end_date | date:"D d F Y"}}</p>

            {% if duplicate_classes %}
                <h3 style="color: red;">WARNING: The following duplicate classes were found!</h3>
                <ul>
                    {% for duplicate in duplicate_classes %}
                        <li><strong>{{ duplicate.class.name }} ({{ duplicate.class.location }})</strong>, {{ duplicate.class.date | date:"D d F Y, g:i a"}} (x {{ duplicate.count}})</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if created_classes %}
                <h3>New Classses</h3>
                <p>The following classes were created :</p>
                <ul>
                {% for class in created_classes %}
                    <li><strong>{{ class.name }}</strong>, {{ class.date | date:"D d F Y, g:i a"}}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No new classes have been created.</p>
            {% endif %}
            {% if existing_classes %}
                <h3>Existing classes</h3>
                <p>The following classes already existed in the system and have
                    not been added again:</p>
                <ul>
                {% for class in existing_classes %}
                    <li><strong>{{ class.name }}</strong>, {{ class.date | date:"D d F Y, g:i a"}}</li>
                {% endfor %}
                </ul>
            {% endif %}

        </div>
    </div>
</div>

</div>
{% endblock %}

timetable/templates/timetable/upload_timetable_form.html
{% extends "admin/base.html" %}
{% load static %}
{% load bootstrap3 %}


{% block extrastyle %}
<link href="{% static 'website/css/admin-extra.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'timetable/css/jquery.datetimepicker.css' %}"/ >

<script src="{% static 'timetable/js/jquery.js' %}"></script>
<script src="{% static 'timetable/js/moment.min.js' %}"></script>
<script src="{% static 'timetable/js/jquery.are-you-sure.js' %}"></script>
<script src="{% static 'timetable/js/jquery.datetimepicker.js' %}"></script>
<script src="{% static 'timetable/js/timetable.js' %}"></script>

{% endblock %}

{% block content %}

<div class="container-fluid row">

<h2>Upload timetable</h2>

    <div class="col-sm-12">

        <div>
        {{ form.media }}
        {% if form.errors %}
            <div class="form-error">
                <p>The operation could not be performed because one or more error(s) occurred.<br />Please resubmit the form after making the following changes:</p>
                <ul>
                {% for field in form %}
                {% if field.errors %}<li>{{ field.name }}: {{ field.errors|striptags }}</li>{% endif %}
                {% endfor %}
                </ul>
            </div>
        {% endif %}

            <div><p>Upload classes from the current timetable for the following date range:</p></div>
            <form method="post">
            {% csrf_token %}
            <div class="upload-timetable-form">
                {{form.as_p}}
            </div>

            <div>
                <button type="submit" class="btn btn-success">Upload</button>
            </div>

            </form>
            </div>

            </div>

    </div>

{% endblock %}