accounts/urls.py
from django.urls import path

from .views import profile, ProfileUpdateView, SignedDataPrivacyCreateView, DisclaimerCreateView, DisclaimerContactUpdateView

app_name = 'accounts'


urlpatterns = [
    path('profile/', profile, name='profile'),
    path('update/', ProfileUpdateView.as_view(), name='update_profile'),
    path(
        'data-privacy-review/', SignedDataPrivacyCreateView.as_view(),
         name='data_privacy_review'
    ),
    path('disclaimer/<int:user_id>/', DisclaimerCreateView.as_view(), name='disclaimer_form'),
    path('emergency-contact/<int:user_id>/update/', DisclaimerContactUpdateView.as_view(), name='update_emergency_contact'),

    path('', profile)
]

booking/urls.py
from django.urls import path


from booking.views import EventListView, EventDetailView, BookingCreateView, \
    already_cancelled, already_paid, \
    BookingListView, \
    BookingHistoryListView, BookingUpdateView, \
    BookingDeleteView, update_booking_cancelled, \
    cancellation_period_past, duplicate_booking, fully_booked, \
    toggle_booking, toggle_waiting_list, booking_details, update_booking_count, \
    outstanding_fees


app_name = 'booking'


urlpatterns = [
    path('my-bookings/', BookingListView.as_view(), name='bookings'),
    path('booking-history/', BookingHistoryListView.as_view(),
        name='booking_history'),
    path('my-bookings/update/<int:pk>/', BookingUpdateView.as_view(),
        name='update_booking'),
    path('my-bookings/update/<int:pk>/cancelled/',
        update_booking_cancelled,
        name='update_booking_cancelled'),
    path('my-bookings/update/<int:pk>/paid/',
        already_paid, name='already_paid'),
    path('my-bookings/cancel/<int:pk>/', BookingDeleteView.as_view(),
        name='delete_booking'),
    path('my-bookings/cancel/<int:pk>/already_cancelled/',
        already_cancelled,
        name='already_cancelled'),
    path('workshops/<slug:event_slug>/cancellation-period-past/',
        cancellation_period_past, name='cancellation_period_past'),
    path('workshops/<slug:event_slug>/duplicate/',
        duplicate_booking, name='duplicate_booking'),
    path('workshops/<slug:event_slug>/full/', fully_booked,
        name='fully_booked'),
    path('workshops/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_event'),
    path('class/<slug:event_slug>/book/', BookingCreateView.as_view(),
        name='book_class'),
    path(
        'workshops/<slug:slug>/', EventDetailView.as_view(),
        name='event_detail'
    ),
    path('outstanding-fees/', outstanding_fees, name="outstanding_fees"),
    path(
        'toggle-booking/<int:event_id>/',
        toggle_booking, name='toggle_booking'
    ),
    path(
        'ajax-toggle-waiting-list/<int:event_id>/',
        toggle_waiting_list, name='toggle_waiting_list'
    ),
    path(
        'update-booking-details/<int:event_id>/',
        booking_details, name='booking_details'
    ),
    path(
        'ajax-update-booking-count/<int:event_id>/',
        update_booking_count, name='update_booking_count'
    ),
    path('', EventListView.as_view(), name='events'),
 ]

polefit/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import CustomLoginView, CustomSignUpView, \
    data_privacy_policy, cookie_policy
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path('', include('website.urls')),
    path(
        'accounts/signup/', CustomSignUpView.as_view(), name='account_signup'
    ),
    path(
        'accounts/login/', CustomLoginView.as_view(), name='account_login'
    ),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    re_path(r'^pf_admin.*', redirect_to_admin, name='redirect_old_link'),
    path('instructor-admin/', include('studioadmin.urls')),
    path('site-admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('payments/ipn-paypal-notify/', include('paypal.standard.ipn.urls')),
    path('payments/', include('payments.urls')),
    path('not-available/', permission_denied, name='permission_denied'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

booking/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.safestring import mark_safe
from django.utils import timezone

from suit.widgets import EnclosedInput

from booking.models import Booking, Event


class BookingCreateForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['event', ]

day = 24
week = day * 7

cancel_choices = (
    (day * 0, '0 hours'),
    (day * 1, '24 hours'),
    (day * 2, '2 days'),
    (day * 3, '3 days'),
    (day * 4, '4 days'),
    (day * 5, '5 days'),
    (day * 6, '6 days'),
    (week, '1 week'),
    (week * 2, '2 weeks'),
    (week * 3, '3 weeks'),
    (week * 4, '4 weeks'),
    (week * 5, '5 weeks'),
    (week * 6, '6 weeks'),
)


class EventForm(forms.ModelForm):

    class Meta:
        widgets = {
            # You can also use prepended and appended together
            'cost': EnclosedInput(prepend=u'\u00A3'),
            'cancellation_period': forms.Select(choices=cancel_choices),
            # 'date': SuitSplitDateTimeWidget()
            }
        help_texts = {
            'cancellation_period': mark_safe(
                'Only applicable if "allow booking cancellation" is '
                'ticked.<br/>'
                '0 hours cancellation period means users can cancel and '
                'request refunds at ANY time up to the time of the '
                'workshop.<br/><br/>'
                'Users will still see an option to cancel their booking, '
                'even if cancellation is not allowed, or the cancellation '
                'period is past.  This allows them to notify you of '
                'non-attendance, re-opens their space for booking, and '
                'notifies the waiting list if applicable.'
            ),
            'allow_booking_cancellation': 'If unticked, users will not be '
                                          'eligible for refunds if they '
                                          'cancel at any time after '
                                          'booking.'
        }


def get_names(event_type='regular_session'):

    def callable():
        NAME_CHOICES = list(set(
            Event.objects.select_related('venue')
            .filter(event_type=event_type, date__gte=timezone.now()).order_by('name')
            .values_list('name', 'name')
        ))
        NAME_CHOICES.insert(0, ('all', 'All'))
        return tuple(NAME_CHOICES)

    return callable


def get_venues(event_type='regular_session'):

    def callable():
        VENUE_CHOICES = list(set(
            Event.objects.select_related('venue')
            .filter(event_type=event_type, date__gte=timezone.now()).order_by('venue')
            .values_list('venue__abbreviation', 'venue__abbreviation')
        ))
        VENUE_CHOICES.insert(0, ('all', 'All locations'))
        return tuple(VENUE_CHOICES)

    return callable


class EventsFilter(forms.Form):

    name = forms.ChoiceField(
        choices=(0,0),
        widget=forms.Select(attrs={'class': 'form-control input-xs'})
    )
    venue = forms.ChoiceField(
        choices=(0,0),
        widget=forms.Select(attrs={'class': 'form-control input-xs'})
    )

    def __init__(self, **kwargs):
        event_type = kwargs.pop('event_type', 'regular_session')
        super(EventsFilter, self).__init__()
        initial = kwargs.get('initial')

        self.fields['name'].choices = get_names(event_type=event_type)
        self.fields['venue'].choices = get_venues(event_type)
        if initial:
            self.fields['name'].initial = initial.get('name', 'all')
            self.fields['venue'].initial = initial.get('venue', 'all')

booking/views/ajax_views.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods
from django.utils import timezone
from django.shortcuts import render, get_object_or_404

from activitylog.models import ActivityLog
from booking.models import Event, Booking, WaitingListUser
from booking.email_helpers import send_email, send_waiting_list_email


@login_required
@require_http_methods(['POST'])
def toggle_booking(request, event_id):

    event = get_object_or_404(Event, pk=event_id)
    ref = request.GET.get('ref')

    if event.event_type == 'regular_session':
        ev_type = 'class'
    else:
        ev_type = 'workshop'

    context = {
        "event": event, "type": ev_type,
        "ref": ref
    }

    existing_booking_status = None
    # check booking status and make new booking
    if Booking.objects.filter(user=request.user, event=event).exists():
        booking = Booking.objects.get(user=request.user, event=event)
        if booking.status == "CANCELLED" or booking.no_show:
            existing_booking_status = "CANCELLED"
        else:
            existing_booking_status = "OPEN"

    # if making a new/reopening booking, make sure the event isn't full or cancelled
    # and abort if user has outstanding fees
    if existing_booking_status != 'OPEN':  # i.e. None (new) or CANCELLED (reopening)
        if request.user.has_outstanding_fees():
            message = f"Action forbidden until outstanding cancellation fees have been resolved"
            return HttpResponseBadRequest(message)

        if not event.spaces_left or event.cancelled:
            message = "Sorry, this {} {}".format(
                ev_type, 'is now full' if not event.spaces_left else "has been cancelled"
            )
            return HttpResponseBadRequest(message)

    if existing_booking_status is None:
        booking = Booking.objects.create(user=request.user, event=event)
    new = existing_booking_status is None

    context['booking'] = booking

    # CANCELLING
    event_was_full = False
    if existing_booking_status == "OPEN":
        event_was_full = event.spaces_left == 0
        # allow 5 mins to properly cancel in case user clicked the wrong button by mistake
        # Otherwise, booking can be fully cancelled if the event allows cancellation AND
        # the cancellation period is not past
        # NOTE: this shouldn't happen, because user should be redirected to confirmation page instead of here if booking
        # is within cancellation period, but it's possible if they're left a page open
        # If not, we let people cancel but leave the booking status OPEN and
        # set to no-show
        booked_within_allowed_time = _booked_within_allowed_time(booking)
        can_cancel = booked_within_allowed_time or (event.allow_booking_cancellation and event.can_cancel())
        if can_cancel:
            booking.status = 'CANCELLED'
        else:
            booking.no_show = True
        action = 'cancelled'

    # REOPENING
    elif existing_booking_status == "CANCELLED":
        booking.status = 'OPEN'
        booking.no_show = False
        action = 'reopened'

    # NEW BOOKING
    elif new:
        booking.status = 'OPEN'
        booking.no_show = False
        action = 'created'

    booking.save()

    ActivityLog.objects.create(
        log='Booking {} {} for "{}" by user {}'.format(
            booking.id, action, booking.event, booking.user.username)
    )

    host = 'http://{}'.format(request.META.get('HTTP_HOST'))
    # send email to user

    # send email to user
    ctx = {
          'booking': booking,
          'event': booking.event,
          'date': booking.event.date.strftime('%A %d %B'),
          'time': booking.event.date.strftime('%H:%M'),
          'ev_type': 'workshop'
    }

    if action == 'cancelled':
        text_template, html_template = (
            'booking/email/booking_cancelled.txt', 'booking/email/booking_cancelled.html'
        )
    else:
        text_template, html_template = (
            'booking/email/booking_received.txt', 'booking/email/booking_received.html'
        )
    send_email(
        request,
        'Booking {} for {}'.format(action, event.name),
        ctx,
        text_template,
        html_template,
        to_list=[booking.user.email],
    )

    # send email to studio if flagged for the event
    if booking.event.email_studio_when_booked:
        send_email(
            request,
            '{} {} has just {} for {}'.format(
                booking.user.first_name, booking.user.last_name,
                'cancelled a booking' if action == 'cancelled' else 'booked',
                booking.event
            ),
            ctx,
            'booking/email/to_studio_booking_cancelled.txt' if action == 'cancelled'
            else 'booking/email/to_studio_booking.txt',
            to_list=[settings.DEFAULT_STUDIO_EMAIL]
        )

    # send waiting list email if event was full before this cancellation
    if event_was_full:
        waiting_list_users = WaitingListUser.objects.filter(event=event)
        if waiting_list_users:
            send_waiting_list_email(
                event,
                [wluser.user for wluser in waiting_list_users],
                host='http://{}'.format(request.META.get('HTTP_HOST'))
            )

    alert_message = {}

    if action in ['created', 'reopened']:
        alert_message['message_type'] = 'success'
        alert_message['message'] = "Booked."
    else:
        alert_message['message_type'] = 'error'
        alert_message['message'] = "Cancelled."

    try:
        waiting_list_user = WaitingListUser.objects.get(
            user=booking.user, event=booking.event
        )
        if action in ['created', 'reopened']:
            waiting_list_user.delete()
            ActivityLog.objects.create(
                log='User {} removed from waiting list '
                'for {}'.format(
                    booking.user.username, booking.event
                )
            )
    except WaitingListUser.DoesNotExist:
        pass

    context["alert_message"] = alert_message

    return render(
        request,
        "booking/includes/book_button_toggle.html",
        context
    )


def _booked_within_allowed_time(booking):
    allowed_datetime = timezone.now() - timedelta(minutes=5)
    return (booking.date_rebooked and booking.date_rebooked > allowed_datetime) \
        or (booking.date_booked > allowed_datetime)


@login_required
def update_booking_count(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    booked = Booking.objects.filter(
        user=request.user, event=event, status='OPEN', no_show=False
    ).exists()

    return JsonResponse(
        {
            'booking_count': "{}/{}".format(event.spaces_left, event.max_participants),
            'full': event.spaces_left == 0,
            'booked': booked
        }
    )


@login_required
def toggle_waiting_list(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)

    if request.user.has_outstanding_fees():
        message = f"Action forbidden until outstanding cancellation fees have been resolved"
        return HttpResponseBadRequest(message)

    # toggle current status
    try:
        waitinglistuser = WaitingListUser.objects.get(user=user, event=event)
        waitinglistuser.delete()
        on_waiting_list = False
    except WaitingListUser.DoesNotExist:
        WaitingListUser.objects.create(user=user, event=event)
        on_waiting_list = True

    return render(
        request,
        "booking/includes/waiting_list_toggle.html",
        {'event': event, 'on_waiting_list': on_waiting_list}
    )


@login_required
def booking_details(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    booking = Booking.objects.get(user=request.user, event=event)

    display_status = booking.status
    if booking.status == 'OPEN' and booking.no_show:
        display_status = 'CANCELLED'
    return JsonResponse(
        {
            'display_status': display_status,
            'status': booking.status,
            'no_show': booking.no_show,
            'display_paid': '<span class="confirmed fas fa-check"></span>' if booking.paid
            else '<span class="not-confirmed fas fa-times"></span>'
        }
    )

booking/views/views_utils.py
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

from accounts.models import DataPrivacyPolicy
from accounts.utils import has_active_data_privacy_agreement


class DataPolicyAgreementRequiredMixin:

    def dispatch(self, request, *args, **kwargs):
        # check if the user has an active disclaimer
        if DataPrivacyPolicy.current_version() > 0 and request.user.is_authenticated \
                and not has_active_data_privacy_agreement(request.user):
            return HttpResponseRedirect(
                reverse('accounts:data_privacy_review') + '?next=' + request.path
            )
        return super().dispatch(request, *args, **kwargs)


class FeesDueMixin:
    def dispatch(self, request, *args, **kwargs):
        # check if the user has outstanding fees
        if request.user.has_outstanding_fees():
            return HttpResponseRedirect(reverse('booking:outstanding_fees'))
        return super().dispatch(request, *args, **kwargs)

booking/templates/booking/already_cancelled.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div>

    <h2>Attempting to cancel for {{ booking.event.name }}</h2>
        <h4>This booking has already been cancelled.</h4>
        <h4><a href="{% url 'booking:bookings' %}">Your bookings</a></h4>

</div>

{% endblock content %}

booking/templates/booking/already_paid.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div>
    <h2>Payment for {{ booking.event }}</h2>
        <h4>This booking has already been paid.</h4>
        <h4><a href="{% url 'booking:bookings' %}">Your bookings</a></h4>
</div>

{% endblock content %}

booking/templates/booking/bookings.html
{% extends "website/_base.html" %}
{% load static %}
{% load bookingtags %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'booking/vanilla-notify.css' %}">
<script type='text/javascript' src="{% static 'booking/vanilla-notify.min.js' %}"></script>
{% endblock %}

{% block content %}

<div class="col-xs-12">

<div class="container-fluid row">
    {% include "booking/includes/fees_due_banner.html" %}

    {% if history %}
        <h1>Past bookings</h1>
    {% else %}
        <h1>Bookings</h1>
    {% endif %}

    {% if event_type == 'regular_session' %}
    <h4>Showing class bookings; see
        {% if history %}
        <a href="{% url 'booking:booking_history' %}?type=workshop">
        {% else %}
        <a href="{% url 'booking:bookings' %}?type=workshop">
        {% endif %}
            workshop bookings</a> instead</h4>
    {% else %}
    <h4>Showing workshop bookings; see
        {% if history %}
        <a href="{% url 'booking:booking_history' %}">
        {% else %}
        <a href="{% url 'booking:bookings' %}">
        {% endif %}
            class bookings</a> instead</h4>
    {% endif %}

    {% if bookings %}
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-transparent">

                <div class="table-responsive">
                    <table class="table table-book-classes">
                        <tr class="panel-heading">
                            {% if not history %}
                            <th> </th>
                            {% endif %}
                            <th>Date</th>
                            <th>Booking</th>
                            <th>Location</th>
                            <th class="table-center">Status</th>
                            <th class="table-center">Paid</th>
                        </tr>

                        {% if event_type == 'regular_session' %}
                            {% for booking in bookings %}
                                <tr id='booked-{{ booking.event.id }}-row' {% if booking_status_display|lookup:booking.id == 'CANCELLED' %}class='expired'{% endif %}>
                                    {% if not history %}
                                        <td class="table-center">
                                        {% if booking.event.cancelled %}
                                            CLASS CANCELLED
                                        {% elif user.has_outstanding_fees %}
                                            {% include "booking/includes/outstanding_fee_disabled_buttons.html" %}
                                        {% elif event.bookable and not event.can_cancel %}
                                            {% if booking.status == 'OPEN' and not booking.no_show %}
                                                <a class="btn table-btn btn-danger cancel_button" href="{% url 'booking:delete_booking' booking.id %}">Cancel</a>
                                            {%  else %}
                                                <a class="btn table-btn btn-success rebook_button" href="{% url 'booking:book_class' booking.event.slug %}">Rebook</a>
                                            {% endif %}
                                        {% elif booking.status == 'OPEN' and not booking.no_show or booking.event.bookable %}
                                            <span
                                                id="book_{{ booking.event.id }}"
                                                data-event_id="{{ booking.event.id }}"
                                                data-ref="bookings"
                                                class="td_ajax_book_btn">
                                            {% include "booking/includes/book_button_toggle.html" %}
                                            </span>
                                        {% else %}
                                            <span
                                                id="waiting_list_button_{{ booking.event.id }}"
                                                data-event_id="{{ booking.event.id }}"
                                                class="td_ajax_waiting_list_btn">
                                            {% include "booking/includes/waiting_list_toggle.html" %}
                                            </span>
                                        {% endif %}
                                        </td>

                                    {% endif %}

                                    <td>{{ booking.event.date |  date:"D d M H:i" }}</td>
                                    <td>{{ booking.event.name }}</td>
                                    <td>{{ booking.event.venue.abbreviation }}</td>
                                    <td class="table-center"><span id="booked-{{ booking.event.id }}-status">{{ booking_status_display|lookup:booking.id  }}</span></td>
                                    <td class="table-center"><span id="booked-{{ booking.event.id }}-paid">
                                        {% if booking.paid %}<span class="confirmed fas fa-check"></span>{% else %}<span class="not-confirmed fas fa-times"></span>{% endif %}
                                    </span></td>
                                </tr>
                            {% endfor %}

                        {% else %}

                            {% for booking in bookings %}
                                <tr {% if booking_status_display|lookup:booking.id  == 'CANCELLED' %}class='expired'{% endif %}>
                                     {% if not history %}
                                        <td>
                                            {% if not booking.paid %}
                                            <div class="inc-btm-space table-btn">
                                                {% if booking_status_display|lookup:booking.id  == 'OPEN' %}
                                                    {% if booking.id in paypalforms %}
                                                        {% include 'payments/bookinglistpayment.html' %}
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                            {% endif %}
                                            {% if booking_status_display|lookup:booking.id == 'OPEN'%}
                                            <a href="{% url 'booking:delete_booking' booking.pk %}">
                                                <div class="btn btn-danger table-btn booking-btn">Cancel booking</div>
                                            </a>
                                            {% elif booking.event.cancelled %}
                                                WORKSHOP CANCELLED
                                            {% elif not booking.event.bookable %}
                                                {% if not booking.event.spaces_left %}
                                                    {% if booking.id in on_waiting_list_booking_ids_list %}
                                                        {% if user.has_outstanding_fees %}
                                                            <button class="btn btn-warning table-btn booking-btn disabled" id="leave_waiting_list_button_disabled">Leave waiting list</button>
                                                        {% else %}
                                                            <form class="wl-table-form" action="{% url 'booking:book_event' booking.event.slug %}" method="get">
                                                                <input id='leave_waiting_list_button' class="btn btn-warning table-btn booking-btn" type="submit" value="Leave waiting list" name="leave waiting list"/>
                                                                <input class="hide" type="text" name="bookings" value="bookings" />
                                                            </form>
                                                        {% endif %}
                                                    {% else %}
                                                        {% if user.has_outstanding_fees %}
                                                            <button class="btn btn-success table-btn booking-btn disabled" id="join_waiting_list_button_disabled">Join waiting list</button>
                                                        {% else %}
                                                            <form class="wl-table-form" action="{% url 'booking:book_event' booking.event.slug %}" method="get">
                                                                <input id='join_waiting_list_button' class="btn btn-success table-btn booking-btn" type="submit" value="Join waiting list" name="join waiting list"/>
                                                                <input class="hide" type="text" name="bookings" value="bookings" />
                                                            </form>
                                                        {% endif %}
                                                    {% endif %}
                                                {% elif booking_status_display|lookup:booking.id  == 'CANCELLED' %}
                                                    <div type="button" id="rebook_button_disabled" class="btn btn-success table-btn booking-btn disabled">Rebook</div>
                                                {% endif %}
                                            {% else %}
                                                <a href="{% url 'booking:book_event' booking.event.slug %}">
                                                    <div type="button" id="rebook_button{% if user.has_outstanding_fees %}_disabled{% endif %}" class="btn btn-success table-btn booking-btn {% if user.has_outstanding_fees %}disabled{% endif %}">Rebook</div></a>
                                            {% endif %}
                                        </td>
                                    {% endif %}

                                    <td>{{ booking.event.date |  date:"D d M H:i" }}</td>
                                    <td>
                                        <a href="{% url 'booking:event_detail' booking.event.slug %}">
                                            {{ booking.event.name }}</a>
                                    </td>
                                    <td>{{ booking.event.venue.abbreviation }}</td>
                                    <td>{{ booking_status_display|lookup:booking.id }}</td>
                                    <td class="hidden-sm hidden-xs table-center">£{{ booking.event.cost }}</td>
                                    <td class="table-center">{{ booking|format_paid_status }}</td>

                                </tr>
                            {% endfor %}
                        {% endif %}
                    </table>
                    {% include 'booking/includes/pagination.html' %}
                </div>


        </div>
        </div>
    </div>
    {% else %}
        {% if history %}
            <p>You do not have any past bookings.</p>
        {% else %}
            <p>You do not have any upcoming bookings.</p>
        {% endif %}
    {% endif %}

</div>

</div>
{% endblock content %}


{% block extrascripts %}
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script type='text/javascript' src="{% static 'booking/js/events_booking_ajax.js' %}"></script>
<script type='text/javascript' src="{% static 'booking/js/toggle_waiting_list_ajax.js' %}"></script>

{% endblock %}

booking/templates/booking/cancellation_period_past.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div>

    <h2>Attempting to cancel booking for <a href="{% url 'booking:event_detail' event.slug %}">{{ event.name }}</a> on {{ event.date | date:"D d F, g:i a" }}</h2>

        <h4>Bookings cannot be cancelled for this event because the cancellation period has now passed.</h4>
        <h4>For further information, please contact
        <a href="mailto:{{ event.contact_email }}?Subject=Enquiry regarding booking for {{ event.name }}" target="_blank">{{ event.contact_email }}</a>
        </h4>

</div>

{% endblock content %}

booking/templates/booking/duplicate_booking.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div>

    <h2>Attempting to book for {{ event.name }}</h2>
        <h4>You have already booked for this {{ ev_type }}.</h4>
        <h4>See <a href="{% url 'booking:bookings' %}">your bookings</a> for details.</h4>

</div>

{% endblock content %}

booking/templates/booking/outstanding_fees.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div>

    <h2>Your account is currently locked</h2>
    <p>You have outstanding cancellation fees of £{{ fees }}. You cannot make any
        bookings until this has been resolved.
    </p>
    <p>Please contact the studio to arrange payment and to unlock your account.</p>

</div>

{% endblock content %}